language: php
php:
  - "5.5"
  - "5.6"
  - "7.1"
  - "hhvm"

before_script:
  - composer install

script: 
  - bin/phpunit --coverage-text

matrix:
     allow_failures:
         - php: "hhvm"
branches:
  only:
    - master
 
